"""Auto migration

Revision ID: 1d88ca2c8c80
Revises: 6fd4bd1a7c31
Create Date: 2025-11-13 10:32:38.097992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d88ca2c8c80'
down_revision: Union[str, Sequence[str], None] = '6fd4bd1a7c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
