"""Update new columns in tenants, device

Revision ID: 3c6507120dec
Revises: 54ca5767ecd5
Create Date: 2025-12-17 20:27:31.331585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c6507120dec'
down_revision: Union[str, Sequence[str], None] = '54ca5767ecd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('serial_no', sa.String(), nullable=False))
    op.add_column('devices', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('protocol', sa.Enum('MQTT', 'HTTP', 'COAP', name='protocol_enum'), nullable=False))
    op.add_column('devices', sa.Column('is_online', sa.Boolean(), nullable=True))
    op.add_column('devices', sa.Column('device_mode', sa.String(), nullable=False))
    op.add_column('devices', sa.Column('last_seen_at', sa.DateTime(), nullable=True))
    op.add_column('devices', sa.Column('device_type_id', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('mqtt_client_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_devices_tenant_id'), table_name='devices')
    op.create_index(op.f('ix_devices_device_type_id'), 'devices', ['device_type_id'], unique=False)
    op.create_index(op.f('ix_devices_mqtt_client_id'), 'devices', ['mqtt_client_id'], unique=False)
    op.create_index(op.f('ix_devices_room_id'), 'devices', ['room_id'], unique=False)
    op.create_index(op.f('ix_devices_serial_no'), 'devices', ['serial_no'], unique=True)
    op.drop_constraint(op.f('devices_tenant_id_fkey'), 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'mqtt_clients', ['mqtt_client_id'], ['id'])
    op.create_foreign_key(None, 'devices', 'device_types', ['device_type_id'], ['id'])
    op.drop_column('devices', 'tenant_id')
    op.drop_column('devices', 'status')
    op.drop_column('devices', 'type')
    op.add_column('tenants', sa.Column('address', sa.String(), nullable=True))
    op.alter_column('users', 'failed_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'failed_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tenants', 'address')
    op.add_column('devices', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('devices', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key(op.f('devices_tenant_id_fkey'), 'devices', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_devices_serial_no'), table_name='devices')
    op.drop_index(op.f('ix_devices_room_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_mqtt_client_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_type_id'), table_name='devices')
    op.create_index(op.f('ix_devices_tenant_id'), 'devices', ['tenant_id'], unique=False)
    op.drop_column('devices', 'mqtt_client_id')
    op.drop_column('devices', 'device_type_id')
    op.drop_column('devices', 'last_seen_at')
    op.drop_column('devices', 'device_mode')
    op.drop_column('devices', 'is_online')
    op.drop_column('devices', 'protocol')
    op.drop_column('devices', 'ip_address')
    op.drop_column('devices', 'serial_no')
    # ### end Alembic commands ###
