"""Add profile-pic to user

Revision ID: 54ca5767ecd5
Revises: dcf7bb6e547f
Create Date: 2025-11-17 13:06:20.789709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ca5767ecd5'
down_revision: Union[str, Sequence[str], None] = 'dcf7bb6e547f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.String(), nullable=True))
    op.alter_column('users', 'failed_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'failed_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###
