"""Add failed_attempts to user

Revision ID: a9f6fad284f3
Revises: 
Create Date: 2025-11-13 08:19:26.062676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f6fad284f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_devices_tenant_id'), 'devices', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'devices', 'tenants', ['tenant_id'], ['id'])
    op.add_column('rooms', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_rooms_tenant_id'), 'rooms', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'rooms', 'tenants', ['tenant_id'], ['id'])
    op.add_column('users', sa.Column('failed_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('lockout_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lockout_until')
    op.drop_column('users', 'failed_attempts')
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_index(op.f('ix_rooms_tenant_id'), table_name='rooms')
    op.drop_column('rooms', 'tenant_id')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_index(op.f('ix_devices_tenant_id'), table_name='devices')
    op.drop_column('devices', 'tenant_id')
    # ### end Alembic commands ###
